/**
 * What each kind of record and each field of the sync is called in German, as
 * a conflict and every other screen that only has the raw name show it.
 *
 * Here and not in the web package, so that the server's tests can hold it
 * against the schema: every entity of the sync policies and every field a
 * device may write has a name, and a new column without one turns a test red
 * instead of showing up as `performedOn` on a screen in a cellar (#221).
 */

export const syncEntityNames: Readonly<Record<string, string>> = {
  customers: 'Kunde',
  contacts: 'Ansprechpartner',
  sites: 'Objekt',
  installations: 'Anlage',
  distribution_boards: 'Verteiler',
  board_sections: 'Feld',
  circuits: 'Stromkreis',
  equipment: 'Betriebsmittel',
  inverters: 'Wechselrichter',
  pv_strings: 'String',
  pv_modules: 'Modul',
  jobs: 'Auftrag',
  documents: 'Beleg',
  document_lines: 'Belegposition',
  document_signatures: 'Unterschrift',
  tasks: 'Aufgabe',
  attachments: 'Datei',
  attachment_versions: 'Fassung einer Datei',
  time_entries: 'Zeiteintrag',
  document_sources: 'Grundlage einer Rechnung',
  job_assignments: 'Zuordnung zu einem Auftrag',
  form_records: 'Protokoll',
  form_definitions: 'Formular',
}

export const syncFieldNames: Readonly<Record<string, string>> = {
  name: 'Name',
  kind: 'Art',
  status: 'Status',
  designation: 'Bezeichnung',
  description: 'Beschreibung',
  notes: 'Notizen',
  email: 'E-Mail',
  phone: 'Telefon',
  givenName: 'Vorname',
  familyName: 'Nachname',
  role: 'Rolle',
  street: 'Straße',
  houseNumber: 'Hausnummer',
  postalCode: 'PLZ',
  city: 'Ort',
  country: 'Land',
  manufacturer: 'Hersteller',
  model: 'Typ',
  serialNumber: 'Seriennummer',
  commissionedOn: 'In Betrieb seit',
  warrantyEndsOn: 'Gewährleistung bis',
  customerId: 'Kunde',
  siteId: 'Objekt',
  jobId: 'Auftrag',
  title: 'Titel',
  dueOn: 'Fällig am',
  assigneeUserId: 'Verantwortlich',
  installationId: 'Anlage',
  documentId: 'Beleg',
  number: 'Nummer',
  quantityMilli: 'Menge',
  unit: 'Einheit',
  unitPriceCents: 'Einzelpreis',
  netCents: 'Netto',
  vatRate: 'Steuersatz',
  taxTreatment: 'Steuerfall',
  documentDate: 'Belegdatum',
  subject: 'Betreff',
  introText: 'Text über den Positionen',
  closingText: 'Text unter den Positionen',
  position: 'Stelle',
  predecessorDocumentId: 'Vorgänger',
  serviceFrom: 'Leistung ab',
  serviceUntil: 'Leistung bis',
  vatId: 'USt-IdNr.',
  buyerReference: 'Käuferreferenz',
  isBusiness: 'Unternehmen',
  isConstructionServiceRecipient: 'Bauleistungsempfänger',
  signerName: 'Unterschrieben von',
  signedAt: 'Unterschrieben am',
  deviceInfo: 'Gerät',
  path: 'Unterschrift',
  contentFingerprint: 'Unterschriebener Stand',
  location: 'Ort',
  distributionBoardId: 'Verteiler',
  boardSectionId: 'Feld',
  circuitId: 'Stromkreis',
  consumer: 'Verbraucher',
  overcurrentDevice: 'Schutzeinrichtung',
  tripCharacteristic: 'Charakteristik',
  ratedCurrentMilli: 'Nennstrom',
  rcdType: 'RCD-Typ',
  ratedResidualCurrentMilli: 'Bemessungsdifferenzstrom',
  cableType: 'Leitungstyp',
  cableCores: 'Aderzahl',
  cableCrossSectionMilli: 'Querschnitt',
  cableLengthMilli: 'Leitungslänge',
  cableInstallationMethod: 'Verlegeart',
  attachmentId: 'Datei',
  fileName: 'Dateiname',
  mediaType: 'Dateityp',
  sizeBytes: 'Größe',
  sha256: 'Prüfsumme',
  previewSha256: 'Vorschau',
  createdBy: 'Angelegt von',
  taxExemptionCertificateNumber: 'Freistellungsbescheinigung',
  taxExemptionValidUntil: 'Freistellung gültig bis',
  parentJobId: 'Übergeordneter Auftrag',
  predecessorJobId: 'Folgt auf',
  inverterId: 'Wechselrichter',
  pvStringId: 'String',
  paymentTermDays: 'Zahlungsziel',
  fieldsVersion: 'Fassung der eigenen Felder',
  fieldValues: 'Eigene Felder',
  sourceDocumentId: 'Regiebericht',
  releasedAt: 'Freigegeben am',
  userId: 'Person',
  startedAt: 'Beginn',
  endedAt: 'Ende',
  note: 'Notiz',
  correctsEntryId: 'Korrigiert',
  withdrawn: 'Gestrichen',
  startLatitudeMicro: 'Breitengrad beim Start',
  startLongitudeMicro: 'Längengrad beim Start',
  endLatitudeMicro: 'Breitengrad beim Stopp',
  endLongitudeMicro: 'Längengrad beim Stopp',
  key: 'Formular',
  definition: 'Felder des Formulars',
  definitionKey: 'Formular',
  definitionVersion: 'Fassung des Formulars',
  performedOn: 'Geprüft am',
  values: 'Eingetragene Werte',
}
