import type { Pool } from 'pg'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'

import {
  applyMigrations,
  connect,
  enumNames,
  functionNames,
  resetSchema,
  revertAllMigrations,
  tableNames,
} from './test-database.js'

let pool: Pool

beforeAll(async () => {
  pool = await connect()
})

afterAll(async () => {
  await pool.end()
})

describe('the migrations', () => {
  it('run against an empty database and back again', async () => {
    await resetSchema(pool)
    expect(await tableNames(pool)).toEqual([])

    await applyMigrations()

    const tables = await tableNames(pool)
    expect(tables).toContain('customers')
    expect(tables).toContain('sites')
    expect(tables).toContain('installations')
    expect(tables).toContain('jobs')
    expect(tables).toContain('documents')
    expect(await enumNames(pool)).toContain('customer_kind')
    expect(await functionNames(pool)).toContain('verify_audit_chain')

    await revertAllMigrations(pool)

    // Nothing left behind. This is the part that catches a rollback which
    // forgot a table, a type or a function: the check is what the database
    // says, not a list somebody kept in sync by hand.
    //
    // The function is the one that fails loudest and latest. Seven of the nine
    // in the migrations are created without `OR REPLACE`, so a forgotten
    // rollback does not just leave something behind, it makes the next run
    // forward fail with "function already exists", and that run is exactly
    // what a down file exists for.
    expect(await tableNames(pool)).toEqual([])
    expect(await enumNames(pool)).toEqual([])
    expect(await functionNames(pool)).toEqual([])
  })

  it('leaves the keys as UUIDv7, generated by the database', async () => {
    await resetSchema(pool)
    await applyMigrations()

    const { rows } = await pool.query<{ id: string }>(
      "insert into tenants (name) values ('Probe') returning id",
    )

    // Version 7 puts the version nibble at the start of the third group.
    expect(rows[0]?.id).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-/)
  })
})
