-- Takes back 0066, and there is nothing to take back. A value cannot be taken
-- out of an enum, and an unused one does no harm; the same choice as in the
-- rollbacks of 0036 and 0043, which kept their units too.
